name: Build and Push Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: test-cicd
  USER_DOCKERHUB: ${{secrets.USER}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository/code
        uses: actions/checkout@v4

      - name: Dockerhub Login
        run: |
          echo "${{ secrets.TOKEN }}"  | docker login -u ${{env.USER_DOCKERHUB}} --password-stdin

      - name: Docker build
        run: |
          docker build -t ${{env.USER_DOCKERHUB}}/${{env.IMAGE_NAME}}:${GITHUB_SHA} \
          -t ${{env.USER_DOCKERHUB}}/${{env.IMAGE_NAME}}:latest .

      - name: Docker push
        run: |
          docker push ${{env.USER_DOCKERHUB}}/${{env.IMAGE_NAME}}:${GITHUB_SHA}
          docker push ${{env.USER_DOCKERHUB}}/${{env.IMAGE_NAME}}:latest